import type { Category, Listing } from './types'

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Electronice', slug: 'electronice', icon: null, parent_id: null },
  { id: 'cat-2', name: 'Imobiliare', slug: 'imobiliare', icon: null, parent_id: null },
  { id: 'cat-3', name: 'Auto-Moto', slug: 'auto-moto', icon: null, parent_id: null },
  { id: 'cat-4', name: 'Modă & Îmbrăcăminte', slug: 'moda-imbracaminte', icon: null, parent_id: null },
  { id: 'cat-5', name: 'Casa & Grădină', slug: 'casa-gradina', icon: null, parent_id: null },
]

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    title: 'iPhone 15 Pro Max 256GB - Stare excelentă',
    description: 'Telefon în stare perfectă, cu garanție.',
    price: 4500,
    location: 'București',
    images: [
      'https://placehold.co/400x300?text=iPhone+15+Pro+Max+-+Front',
      'https://placehold.co/400x300?text=iPhone+15+Pro+Max+-+Back',
      'https://placehold.co/400x300?text=iPhone+15+Pro+Max+-+Detail',
    ],
    status: 'activ',
    is_promoted: true,
    category_id: 'cat-1',
    category: null,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Apartament 2 camere, centru Cluj',
    description: 'Apartament modern, recent renovat.',
    price: 95000,
    location: 'Cluj-Napoca',
    images: [
      'https://placehold.co/400x300?text=Apartament+2+Camere+Cluj+-+Living',
      'https://placehold.co/400x300?text=Apartament+2+Camere+Cluj+-+Dormitor',
      'https://placehold.co/400x300?text=Apartament+2+Camere+Cluj+-+Bucatarie',
    ],
    status: 'activ',
    is_promoted: true,
    category_id: 'cat-2',
    category: null,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Volkswagen Golf 7, 1.6 TDI',
    description: 'Mașină întreținută la zi.',
    price: 12000,
    location: 'Timișoara',
    images: [
      'https://placehold.co/400x300?text=Volkswagen+Golf+7+-+Front',
      'https://placehold.co/400x300?text=Volkswagen+Golf+7+-+Interior',
      'https://placehold.co/400x300?text=Volkswagen+Golf+7+-+Rear',
    ],
    status: 'activ',
    is_promoted: true,
    category_id: 'cat-3',
    category: null,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Geantă Louis Vuitton autentică',
    description: 'Geantă pentru femei, utilizată elegant.',
    price: 2500,
    location: 'București',
    images: [
      'https://placehold.co/400x300?text=Geanta+Louis+Vuitton+-+Front',
      'https://placehold.co/400x300?text=Geanta+Louis+Vuitton+-+Inside',
      'https://placehold.co/400x300?text=Geanta+Louis+Vuitton+-+Detail',
    ],
    status: 'activ',
    is_promoted: true,
    category_id: 'cat-4',
    category: null,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Laptop Dell XPS 15 - i7, 16GB RAM',
    description: 'Performanță excelentă pentru muncă și gaming.',
    price: 3500,
    location: 'Iași',
    images: [
      'https://placehold.co/400x300?text=Dell+XPS+15+-+Open',
      'https://placehold.co/400x300?text=Dell+XPS+15+-+Keyboard',
      'https://placehold.co/400x300?text=Dell+XPS+15+-+Ports',
    ],
    status: 'activ',
    is_promoted: false,
    category_id: 'cat-1',
    category: null,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Scaun gaming ergonomic',
    description: 'Scaun nou, nedesfacut.',
    price: 650,
    location: 'București',
    images: [
      'https://placehold.co/400x300?text=Scaun+Gaming+-+Front',
      'https://placehold.co/400x300?text=Scaun+Gaming+-+Side',
      'https://placehold.co/400x300?text=Scaun+Gaming+-+Back',
    ],
    status: 'activ',
    is_promoted: false,
    category_id: 'cat-5',
    category: null,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    title: 'Tabelă electrică Yamaha',
    description: 'Tabelă în stare foarte bună.',
    price: 1200,
    location: 'Brașov',
    images: [
      'https://placehold.co/400x300?text=Yamaha+Tabla+-+Set',
      'https://placehold.co/400x300?text=Yamaha+Tabla+-+Closeup',
      'https://placehold.co/400x300?text=Yamaha+Tabla+-+Pedale',
    ],
    status: 'activ',
    is_promoted: false,
    category_id: 'cat-1',
    category: null,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    title: 'Mobilier living complet',
    description: 'Canapea + 2 fotolii + masa de cafea.',
    price: 2800,
    location: 'Constanța',
    images: [
      'https://placehold.co/400x300?text=Mobilier+Living+-+Canapea',
      'https://placehold.co/400x300?text=Mobilier+Living+-+Fotolii',
      'https://placehold.co/400x300?text=Mobilier+Living+-+Masa',
    ],
    status: 'activ',
    is_promoted: false,
    category_id: 'cat-5',
    category: null,
    created_at: new Date().toISOString(),
  },
]

export const MOCK_COUNT_BY_CATEGORY: Record<string, number> = {
  'cat-1': 3,
  'cat-2': 1,
  'cat-3': 1,
  'cat-4': 1,
  'cat-5': 2,
}
